<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="sakshi" ignored="0" name="Test1" tests="4" failures="2" timestamp="27 Mar 2021 21:52:37 GMT" time="26.053" errors="0">
  <testcase name="LoginFreeCRM" time="0.704" classname="com.sanyam.testproject.LoginPageTest"/>
  <testcase name="testSuccess" time="0.002" classname="com.sanyam.testproject.LoginPageTest"/>
  <testcase name="testCase2" time="1.293" classname="com.sanyam.testproject.LoginPageTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Test Fail 1-C:\Java_Selenium_Items\My_Workspace\Repo_TestNGProjectWithJava\TestNGProjectWithJava\ScreenShot\Fail2_Sun_Mar_28_03_22_36_IST_2021.png,
	Test Fail 2">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Test Fail 1-C:\Java_Selenium_Items\My_Workspace\Repo_TestNGProjectWithJava\TestNGProjectWithJava\ScreenShot\Fail2_Sun_Mar_28_03_22_36_IST_2021.png,
Test Fail 2
at com.sanyam.testproject.LoginPageTest.testCase2(LoginPageTest.java:68)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- testCase2 -->
  <testcase name="testCase2" time="1.311" classname="com.sanyam.testproject.LoginPageTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.sanyam.frameworkpackage.ExtentManager.getScreenshot(ExtentManager.java:48)
at com.sanyam.frameworkpackage.TestListners.onTestFailure(TestListners.java:48)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testCase2 -->
</testsuite> <!-- Test1 -->
