<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="2" ignored="0" total="7" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="55472" started-at="2021-03-28T01:21:16Z" finished-at="2021-03-28T01:22:11Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="55472" started-at="2021-03-28T01:21:16Z" finished-at="2021-03-28T01:22:11Z">
      <class name="com.sanyam.testproject.LoginPageTest">
        <test-method status="PASS" signature="setUp(org.testng.ITestContext)[pri:0, instance:com.sanyam.testproject.LoginPageTest@3891771e]" name="setUp" is-config="true" duration-ms="26687" started-at="2021-03-28T06:51:16Z" finished-at="2021-03-28T06:51:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@4efcf8a]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="LoginFreeCRM()[pri:0, instance:com.sanyam.testproject.LoginPageTest@3891771e]" name="LoginFreeCRM" duration-ms="2080" started-at="2021-03-28T06:51:43Z" finished-at="2021-03-28T06:51:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginFreeCRM -->
        <test-method status="PASS" signature="testSuccess()[pri:1, instance:com.sanyam.testproject.LoginPageTest@3891771e]" name="testSuccess" duration-ms="3" started-at="2021-03-28T06:51:45Z" finished-at="2021-03-28T06:51:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSuccess -->
        <test-method status="FAIL" signature="testCase2()[pri:2, instance:com.sanyam.testproject.LoginPageTest@3891771e]" name="testCase2" duration-ms="2099" started-at="2021-03-28T06:52:06Z" finished-at="2021-03-28T06:52:08Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	Test Fail 1-C:\Java_Selenium_Items\My_Workspace\Repo_TestNGProjectWithJava\TestNGProjectWithJava\ScreenShot\Fail2_Sun_Mar_28_06_52_07_IST_2021.png,
	Test Fail 2]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	Test Fail 1-C:\Java_Selenium_Items\My_Workspace\Repo_TestNGProjectWithJava\TestNGProjectWithJava\ScreenShot\Fail2_Sun_Mar_28_06_52_07_IST_2021.png,
	Test Fail 2
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.sanyam.testproject.LoginPageTest.testCase2(LoginPageTest.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase2 -->
        <test-method status="FAIL" signature="testCase3()[pri:3, instance:com.sanyam.testproject.LoginPageTest@3891771e]" name="testCase3" duration-ms="10" started-at="2021-03-28T06:52:10Z" finished-at="2021-03-28T06:52:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed to check Failure Scenario]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed to check Failure Scenario
	at org.testng.Assert.fail(Assert.java:93)
	at com.sanyam.testproject.LoginPageTest.testCase3(LoginPageTest.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase3 -->
        <test-method status="SKIP" signature="testSkip()[pri:4, instance:com.sanyam.testproject.LoginPageTest@3891771e]" name="testSkip" duration-ms="1" started-at="2021-03-28T06:52:10Z" finished-at="2021-03-28T06:52:10Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Testig Skip test]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Testig Skip test
	at com.sanyam.testproject.LoginPageTest.testSkip(LoginPageTest.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSkip -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.sanyam.testproject.LoginPageTest@3891771e]" name="teardown" is-config="true" duration-ms="1162" started-at="2021-03-28T06:52:10Z" finished-at="2021-03-28T06:52:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.sanyam.testproject.LoginPageTest -->
      <class name="com.sanyam.testproject.HomePageTest">
        <test-method status="PASS" signature="Setup(org.testng.ITestContext)[pri:0, instance:com.sanyam.testproject.HomePageTest@78ac1102]" name="Setup" is-config="true" duration-ms="19965" started-at="2021-03-28T06:51:45Z" finished-at="2021-03-28T06:52:05Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@4efcf8a]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Setup -->
        <test-method status="PASS" signature="veriftLoggedInUSerTest()[pri:1, instance:com.sanyam.testproject.HomePageTest@78ac1102]" name="veriftLoggedInUSerTest" duration-ms="1202" started-at="2021-03-28T06:52:05Z" finished-at="2021-03-28T06:52:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- veriftLoggedInUSerTest -->
        <test-method status="PASS" signature="contactsButtonTest()[pri:2, instance:com.sanyam.testproject.HomePageTest@78ac1102]" name="contactsButtonTest" duration-ms="478" started-at="2021-03-28T06:52:09Z" finished-at="2021-03-28T06:52:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- contactsButtonTest -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.sanyam.testproject.HomePageTest@78ac1102]" name="teardown" is-config="true" duration-ms="666" started-at="2021-03-28T06:52:09Z" finished-at="2021-03-28T06:52:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.sanyam.testproject.HomePageTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
